# -*- coding: UTF-8 -*-


PROJECT_NAME = "Sylveon"

INPUT_DIRECTORY = "_Input"
OUTPUT_DIRECTORY = "_Output"

ENABLE_CONSOLE_LOGGER = True
ENABLE_FILE_LOGGER = True

LOGGER_FILE_NAME = "{PROJECT_NAME}.log".format(PROJECT_NAME = PROJECT_NAME)
LOGGER_FILE_MODE = "a"
LOGGER_FILE_SIZE = 10 * 1024 * 1024
